### PR TITLE
Unfinished questions in 3.4

### PR DESCRIPTION
**Pull request by jesseli2002**
@UlisseMini I'm hoping you can look over 3.4.9c) before merging since it's a fairly involved construction and I want to make sure that what I wrote is understandable.

### CODE REVIEW

**Comment by UlisseMini** [comment]
For 3.4.9c) would it be a correct summary to say we take $r_{2n}$ in such a way that (for some $\epsilon > 0$ around $\sqrt{2}$)
$$\bigcup_{n=1}^\infty V_{\epsilon_{2n}}(r_{2n}) = V_{\epsilon}(\sqrt{2}) \setminus \{\sqrt{2}\}$$
(this should be possible since the total measure of all the $V_{\epsilon_{2n}}$ is positive) hence this would isolate $\sqrt{2} \in F$. then the other part of the sequence $r_{2n-1}$ can be used to enumerate the other rationals.

As for how we construct $r_{2n}$ I believe you can prove a Lemma that looks something like
Lemma: Let $(\epsilon_n)$ be a decreasing sequence where each $\epsilon_n > 0$ and total measure $r = \Sigma \epsilon_n \lt \infty$. I claim for any interval $(0,L)$ with $L \lt r$ there exists $x_n \in (0,L)$ such that
$$(0,L) = \bigcup_{n=1}^\infty V_{\epsilon_n}(x_n)$$

Then the Lemma can be used to find $r_{2n}$ (after modification to only allow rationals, which should be straightforward if a little technical)

---

I haven't read the technical proof (and might not if I can find a better one), typically I prefer clearer proofs that skip details the reader can easily fill in (the example I give here is extreme, I'd have to add more details for it to count as a solution)

**Comment by jesseli2002** [comment]
Good point - usually I like to be explicit when first writing a proof to minimize the chances of overlooking some detail and reduce my mental burden, but once I'm done I don't bother simplifying it out of laziness :P 

I've reorganized the proof to use a similar lemma - not sure what `r` was supposed to be but I think I got the point anyways.

**Comment by jesseli2002** [comment]
@UlisseMini Good point - usually I like to be explicit when first writing a proof to minimize the chances of overlooking some detail and reduce my mental burden, but once I'm done I don't bother simplifying it out of laziness :P 

I've reorganized the proof to use a similar lemma - not sure what `r` was supposed to be but I think I got the point anyways.

**Comment by UlisseMini** [comment]
> @UlisseMini Good point - usually I like to be explicit when first writing a proof to minimize the chances of overlooking some detail and reduce my mental burden, but once I'm done I don't bother simplifying it out of laziness :P
> 
> I've reorganized the proof to use a similar lemma - not sure what `r` was supposed to be but I think I got the point anyways.

I'm reading the modified proof and am unable to follow (or at least, unable to follow without spending lots of time), my current thoughts are

image

I believe the (TODO) part shouldn't be *too* hard, or at least, structuring the argument in this way is more understandable (when reading yours I have no idea where the lemma comes from, where it will be used, etc.), and this way has the advantage that people unable to follow the technical bit can still see intuitively why the theorem is true.

I'm fine with merging this though and editing it later when I find time, you signed up to write proofs not exposition :sweat_smile: 

PS: I think you're using induction wrong, proving a claim for all $n \in \mathbf{N}$ is not the same as proving a claim for $n = \infty$ (I believe there was a previous exercise on this)

PS2: Mikinty's original solutions repo seems to have this exercise as 3.4.10, though he doesn't fully solve it
image

**Comment by jesseli2002** [comment]
- The proof is basically that, but I have 3 sequences - one for approaching sqrt(2) from below, one for from above, and one for enumerating other rationals. In other words, I'm splitting the problem of forming a neighbourhood into the part above sqrt(2) and the part below sqrt(2). I've added some exposition to explain the overarching strategy at the start. To be fair, I did ask for you to check if it's understandable :P
- Re: induction to infinity; the step to go from the finite to infinite case just involves looking the definition of an infinite union; I've made that step explicit

**Comment by jesseli2002** [comment]
@UlisseMini Heads up - merged. Let me know if I can clarify further.

**Pull request merged**
