### PR TITLE
1.3.10

### PR DESCRIPTION
**Pull request by jesseli2002**
I should mention - thanks for posting & maintaining this solution set; I'm starting to self-study real analysis and using this to help check my work!

Changes in this PR:
- There's a typo in 1.3.2 a) solution
- Made the solution to 1.3.10 a) more explicit; I figured this would be a bit more rigorous but that might just be personal preference.
- For 1.3.10 c) there's a subtle error around negative numbers, so I changed the cut line to cbrt(2) instead, and left a warning note since I almost made the same mistake

### CODE REVIEW

**Comment by jesseli2002** [comment]
I should also ask, if I'm going to be making more of these PRs - would you prefer me to make one PR per question, or bundle several suggestions into one PR?

**Comment by UlisseMini** [comment]
> I should also ask, if I'm going to be making more of these PRs - would you prefer me to make one PR per question, or bundle several suggestions into one PR?

Doesn't really matter, whatever works for you! 

Also apologies for not merging this today, I was busy (read: procrastinating) I'll try and get to the tomorrow.

**Review by UlisseMini — CHANGES_REQUESTED** [review]
I see the problem with the original but I think cube roots are unintuitive, I think `A = {r : r < sqrt(2)}` and `B = {r : r > sqrt(2)}` would be better / is more understandable.

Technically square roots haven't been rigorously defined, but the idea is what counts not pedantry, it's easy to turn a set defined in terms of square roots into one without.

**Review by UlisseMini — APPROVED** [review]

**Review by UlisseMini — APPROVED** [review]

**Comment by jesseli2002** [comment]
Eh, I don't think cube roots are that bad - e.g. the proof that cbrt(2) is irrational is almost as simple as that for sqrt(2). You're right that sqrt would've been the first thing to think of; I just wanted to avoid needing to tack on an additional statement about negative numbers in the definition of `A` - but that's also personal preference.

I've updated to give sqrt(2) as the main solution, and cbrt(2) as an alternative answer.

**Pull request merged**
